name: bench
on:
  push:
   branches:
     - master

jobs:
  bench:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    env:
      CARGO_INCREMENTAL: 0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Bench
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- --bench --plotting-backend plotters cpu
